# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='prontohex',
            field=models.CharField(max_length=800),
        ),
    ]
