# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_auto_20160929_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='serial_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
